---
common:
  dirs:
    - name: '.config'
    - name: '.shell_custom.d'
  ignore:
    - '.git'
    - '.gitignore'
    - 'README.md'
    - '.config'
    - '.shell_custom.d'

templates:
  template1:
    ignore:
      - '.i3'
      - '.Xresources'

profiles:
  me:
    links:
      - '.config/dunst'
      - '.config/redshift'
      - '.config/redshift.conf'
      - '.shell_custom.d/dockerfunc.sh'
      - '.shell_custom.d/sshagent.sh'
  nox:
    include:
      - 'template1'
